//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zulrah_Rotation_Assistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zulrah_Rotation_Assistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Rotation 1&quot;,
        ///  &quot;Phases&quot;: [
        ///    {
        ///      &quot;Style&quot;: &quot;Passive&quot;,
        ///      &quot;Boss_Location&quot;: &quot;S&quot;,
        ///      &quot;Player_Location&quot;: &quot;SW&quot;,
        ///      &quot;Notes&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;Style&quot;: &quot;Melee&quot;,
        ///      &quot;Boss_Location&quot;: &quot;S&quot;,
        ///      &quot;Player_Location&quot;: &quot;SW&quot;,
        ///      &quot;Notes&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;Style&quot;: &quot;Mage&quot;,
        ///      &quot;Boss_Location&quot;: &quot;S&quot;,
        ///      &quot;Player_Location&quot;: &quot;NE&quot;,
        ///      &quot;Notes&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;Style&quot;: &quot;Ranged&quot;,
        ///      &quot;Boss_Location&quot;: &quot;N&quot;,
        ///      &quot;Player_Location&quot;: &quot;NE&quot;,
        ///      &quot;Notes&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rotation_1 {
            get {
                return ResourceManager.GetString("Rotation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;RotationIndex&quot;: &quot;2&quot;,
        ///  &quot;Phases&quot;: [
        ///    {
        ///      &quot;Style&quot;: &quot;Passive&quot;,
        ///      &quot;Boss_Location&quot;: &quot;S&quot;,
        ///      &quot;Player_Location&quot;: &quot;SW&quot;,
        ///      &quot;Notes&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;Style&quot;: &quot;Melee&quot;,
        ///      &quot;Boss_Location&quot;: &quot;S&quot;,
        ///      &quot;Player_Location&quot;: &quot;SW&quot;,
        ///      &quot;Notes&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;Style&quot;: &quot;Mage&quot;,
        ///      &quot;Boss_Location&quot;: &quot;S&quot;,
        ///      &quot;Player_Location&quot;: &quot;NE&quot;,
        ///      &quot;Notes&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;Style&quot;: &quot;Ranged&quot;,
        ///      &quot;Boss_Location&quot;: &quot;E&quot;,
        ///      &quot;Player_Location&quot;: &quot;NE&quot;,
        ///      &quot;Notes&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rotation_2 {
            get {
                return ResourceManager.GetString("Rotation_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;RotationIndex&quot;: &quot;3&quot;,
        ///  &quot;Phases&quot;: [
        ///    {
        ///      &quot;Style&quot;: &quot;Passive&quot;,
        ///      &quot;Boss_Location&quot;: &quot;S&quot;,
        ///      &quot;Player_Location&quot;: &quot;SW&quot;,
        ///      &quot;Notes&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;Style&quot;: &quot;Ranged&quot;,
        ///      &quot;Boss_Location&quot;: &quot;S&quot;,
        ///      &quot;Player_Location&quot;: &quot;SW&quot;,
        ///      &quot;Notes&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;Style&quot;: &quot;Melee&quot;,
        ///      &quot;Boss_Location&quot;: &quot;S&quot;,
        ///      &quot;Player_Location&quot;: &quot;SE&quot;,
        ///      &quot;Notes&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;Style&quot;: &quot;Mage&quot;,
        ///      &quot;Boss_Location&quot;: &quot;E&quot;,
        ///      &quot;Player_Location&quot;: &quot;NE&quot;,
        ///      &quot;Notes&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rotation_3 {
            get {
                return ResourceManager.GetString("Rotation_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;RotationIndex&quot;: &quot;4&quot;,
        ///  &quot;Phases&quot;: [
        ///    {
        ///      &quot;Style&quot;: &quot;Passive&quot;,
        ///      &quot;Boss_Location&quot;: &quot;S&quot;,
        ///      &quot;Player_Location&quot;: &quot;SW&quot;,
        ///      &quot;Notes&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;Style&quot;: &quot;Mage&quot;,
        ///      &quot;Boss_Location&quot;: &quot;W&quot;,
        ///      &quot;Player_Location&quot;: &quot;SW&quot;,
        ///      &quot;Notes&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;Style&quot;: &quot;Ranged&quot;,
        ///      &quot;Boss_Location&quot;: &quot;N&quot;,
        ///      &quot;Player_Location&quot;: &quot;NE&quot;,
        ///      &quot;Notes&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;Style&quot;: &quot;Mage&quot;,
        ///      &quot;Boss_Location&quot;: &quot;E&quot;,
        ///      &quot;Player_Location&quot;: &quot;NE&quot;,
        ///      &quot;Notes&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rotation_4 {
            get {
                return ResourceManager.GetString("Rotation_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;svg
        ///   xmlns:osb=&quot;http://www.openswatchbook.org/uri/2009/osb&quot;
        ///   xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///   xmlns:cc=&quot;http://creativecommons.org/ns#&quot;
        ///   xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot;
        ///   xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;
        ///   xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///   xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:inkscape=&quot;http://www.inksca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZulrahMap {
            get {
                return ResourceManager.GetString("ZulrahMap", resourceCulture);
            }
        }
    }
}
