//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zulrah_Rotation_Assistant.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("246, 0, 58")]
        public global::System.Drawing.Color MeleeColor {
            get {
                return ((global::System.Drawing.Color)(this["MeleeColor"]));
            }
            set {
                this["MeleeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20, 128, 250")]
        public global::System.Drawing.Color MageColor {
            get {
                return ((global::System.Drawing.Color)(this["MageColor"]));
            }
            set {
                this["MageColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90, 254, 0")]
        public global::System.Drawing.Color RangeColor {
            get {
                return ((global::System.Drawing.Color)(this["RangeColor"]));
            }
            set {
                this["RangeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color JadColor {
            get {
                return ((global::System.Drawing.Color)(this["JadColor"]));
            }
            set {
                this["JadColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90, 250, 0")]
        public global::System.Drawing.Color PassiveColor {
            get {
                return ((global::System.Drawing.Color)(this["PassiveColor"]));
            }
            set {
                this["PassiveColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 253, 253")]
        public global::System.Drawing.Color ZulrahIsland_Color {
            get {
                return ((global::System.Drawing.Color)(this["ZulrahIsland_Color"]));
            }
            set {
                this["ZulrahIsland_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("218, 36, 229")]
        public global::System.Drawing.Color PlayerColor {
            get {
                return ((global::System.Drawing.Color)(this["PlayerColor"]));
            }
            set {
                this["PlayerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ZulrahIsland_BorderColor {
            get {
                return ((global::System.Drawing.Color)(this["ZulrahIsland_BorderColor"]));
            }
            set {
                this["ZulrahIsland_BorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49, 49, 49")]
        public global::System.Drawing.Color MapBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["MapBackgroundColor"]));
            }
            set {
                this["MapBackgroundColor"] = value;
            }
        }
    }
}
