//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zulrah_Rotation_Assistant.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("246, 0, 58")]
        public global::System.Drawing.Color MeleeColor {
            get {
                return ((global::System.Drawing.Color)(this["MeleeColor"]));
            }
            set {
                this["MeleeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20, 128, 250")]
        public global::System.Drawing.Color MageColor {
            get {
                return ((global::System.Drawing.Color)(this["MageColor"]));
            }
            set {
                this["MageColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90, 254, 0")]
        public global::System.Drawing.Color RangeColor {
            get {
                return ((global::System.Drawing.Color)(this["RangeColor"]));
            }
            set {
                this["RangeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color JadColor {
            get {
                return ((global::System.Drawing.Color)(this["JadColor"]));
            }
            set {
                this["JadColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90, 250, 0")]
        public global::System.Drawing.Color PassiveColor {
            get {
                return ((global::System.Drawing.Color)(this["PassiveColor"]));
            }
            set {
                this["PassiveColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 253, 253")]
        public global::System.Drawing.Color ZulrahIsland_Color {
            get {
                return ((global::System.Drawing.Color)(this["ZulrahIsland_Color"]));
            }
            set {
                this["ZulrahIsland_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("218, 36, 229")]
        public global::System.Drawing.Color PlayerColor {
            get {
                return ((global::System.Drawing.Color)(this["PlayerColor"]));
            }
            set {
                this["PlayerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ZulrahIsland_BorderColor {
            get {
                return ((global::System.Drawing.Color)(this["ZulrahIsland_BorderColor"]));
            }
            set {
                this["ZulrahIsland_BorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49, 49, 49")]
        public global::System.Drawing.Color MapBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["MapBackgroundColor"]));
            }
            set {
                this["MapBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public string MeleeVoiceCommand {
            get {
                return ((string)(this["MeleeVoiceCommand"]));
            }
            set {
                this["MeleeVoiceCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public string MageVoiceCommand {
            get {
                return ((string)(this["MageVoiceCommand"]));
            }
            set {
                this["MageVoiceCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public string RangeVoiceCommand {
            get {
                return ((string)(this["RangeVoiceCommand"]));
            }
            set {
                this["RangeVoiceCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Top")]
        public string NorthPositionVoiceCommand {
            get {
                return ((string)(this["NorthPositionVoiceCommand"]));
            }
            set {
                this["NorthPositionVoiceCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public string WestPositionVoiceCommand {
            get {
                return ((string)(this["WestPositionVoiceCommand"]));
            }
            set {
                this["WestPositionVoiceCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public string EastPositionVoiceCommand {
            get {
                return ((string)(this["EastPositionVoiceCommand"]));
            }
            set {
                this["EastPositionVoiceCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bottom")]
        public string SouthPositionVoiceCommand {
            get {
                return ((string)(this["SouthPositionVoiceCommand"]));
            }
            set {
                this["SouthPositionVoiceCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reset")]
        public string ResetVoiceCommand {
            get {
                return ((string)(this["ResetVoiceCommand"]));
            }
            set {
                this["ResetVoiceCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Previous")]
        public string PreviousVoiceCommand {
            get {
                return ((string)(this["PreviousVoiceCommand"]));
            }
            set {
                this["PreviousVoiceCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Next")]
        public string NextVoiceCommand {
            get {
                return ((string)(this["NextVoiceCommand"]));
            }
            set {
                this["NextVoiceCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MapFlipped {
            get {
                return ((bool)(this["MapFlipped"]));
            }
            set {
                this["MapFlipped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public global::System.Globalization.CultureInfo VoiceCommandLanguage {
            get {
                return ((global::System.Globalization.CultureInfo)(this["VoiceCommandLanguage"]));
            }
            set {
                this["VoiceCommandLanguage"] = value;
            }
        }
    }
}
